Use MCNP mesh tally data
cnerg/vr-game pull request #3
Opened 2023-10-01 22:34 UTC by bquan0

### Overview
This PR adds the `RadioactiveTank` scene, which represents a voxelized radiation field based on data generated from a MCNP mesh tally (courtesy of Tim Bohm). A short demo of the new features can be seen in the #svalinn-vr channel on Slack. 

### RadioactiveTank.gd
In `_ready()`, the script loads in the data from `tank10.csv` (not included in repo) into 3 arrays for the bounds of the voxels in the x, y, z directions. It also loads in the centroid (x,y,z), radiation value, and relative error of each voxel into another array.
In `get_radiation()`, the script calculates the index of the voxel that the player is in using the position of the player and the arrays of x, y, and z boundaries, and returns the radiation value of that voxel as well as the centroid of the voxel for display purposes. 

### New debug/visualization feature
For all radioactive objects (Tank and Rod), I added a **red mesh** that highlights the current voxel in the radiation field that the player is in. Currently, for the RadioactiveTank, the red mesh is much smaller than the player mesh, so the player mesh needs to be made invisible in order to see this red mesh. 

### MCNP data size
Something worth noting is that the game now takes around 1m 30s to load due to the large size of the MCNP data. Despite this, there doesn't seem to be any drops in performance when running the game (though I haven't tested it with multiple RadioactiveTanks). The size of the voxels for this MCNP data is 10x15x20cm, which might be too fine grain for the application of a VR game.

### Other notes:
Things not included in this PR:
- The `tank10.csv` file because it's around 200MB. 
- The python script used to generate the `tank10.csv` file from the original MCNP mesh tally `.txt` file because it's not used in the Godot game. Nevertheless, I am open to adding it here or in another repo if it's useful.

Other changes:
- Made the blue and red axes of the radioactive rod not "visible" as it can be confusing for people who pick up this 

As a final aside, the index calculation of the voxel for RadioactiveTank really threw me for a loop because I did it incorrectly for the RadioactiveRod (but it didn't matter there because all the max_indices were the same).

2023-10-02 12:00 UTC, gonuke requested changes
A few suggestions for performance and simplicity

2023-10-02 12:00 UTC, gonuke commented on scripts/RadioactiveTank.gd
> +		x_index = x_index + 1
I recommend implementing a binary search in a function that you can reuse for each dimension.

It will also allow you to return a value of -1 if outside the grid in that dimension.  You can test this first before the search and return early. If so, you can also return early from this function with a null result. If the search returned -1 for out of range, you could just compare the product of the indices already set to 0.

Could also include the translation, or just apply it in the function call.

2023-10-02 12:00 UTC, gonuke commented on scripts/RadioactiveTank.gd
> +		bounds_x.append(float(csv_line[i]) / 100);
It's tempting to suggest a function for this that you can reuse with each dimension.

```
func _parse_dims(csv_line, scale)
    bounds = []
    for i in range(0,csv_line.size())
         bounds.append(csv_line[i] * scale)
    return bounds

scale = 1.0/100
bounds_x = _parse_dims(csv_file.get_csv_line(), scale)
bounds_y = _parse_dims(csv_file.get_csv_line(), scale)
bounds_z = _parse_dims(csv_file.get_csv_line(), scale)
```

2023-10-02 12:00 UTC, gonuke commented on scripts/RadioactiveTank.gd
> +		$CurrentVoxel.visible = false
If you initialize this to false, you can return early from this function without having to worry about setting it.

2023-10-02 12:00 UTC, gonuke commented on scripts/RadioactiveTank.gd
> +		if index != prev_index:
Why not test this before testing if in range?

2023-10-02 12:00 UTC, gonuke commented on scripts/RadioactiveTank.gd
> +				voxel.append(float(csv_line[i]) / 100)
Can a list in this language contain different types? Could it contain a `Vector3` object and also the 2 floats? You only use the centroid data to populate/modify a `Vector3` object, so it would make your later code simpler.

Also remove this magic number in favor of a scaling variable.

2023-10-04 01:40 UTC, bquan0 commented on scripts/RadioactiveTank.gd
> +				voxel.append(float(csv_line[i]) / 100)
Yep, it can. One example already in the code is the return value of the function, where I return an array with a float and a Vector3 (radiation value and centroid respectively). I will apply these changes.

2023-10-04 01:51 UTC, bquan0 commented on scripts/RadioactiveTank.gd
> +		if index != prev_index:
Testing whether we should update the visualization mesh is only needed if the player is in the radiation field (index is in range)

2023-10-04 02:05 UTC, bquan0 commented
- Added the `binary_search()` function
- Added the `get_bounds()` function (renamed from `parse_dims()` to fit the preexisting naming schemes)
- Added `scale` variable in `_ready()` to remove magic number of 100
- Made `radiation_map` store a `Vector3` of the centroids instead of 3 floats for the (x,y,z) positions
- Updated logic in `get_radiation()`, added optimizations now that `radiation_map` stores `Vector3`s

2023-10-04 15:04 UTC, gonuke commented on scripts/RadioactiveTank.gd
> +		if index != prev_index:
Yep - I got that... in the previous structure, I thought this test could come even earlier, but it's moot after your recent updates.

2023-10-04 15:12 UTC, gonuke requested changes
one small simplification

2023-10-04 15:12 UTC, gonuke commented on scripts/RadioactiveTank.gd
> +				voxel.append(float(csv_line[i]))
```suggestion
		# first 3 values are x,y,z of centroid in cm, so multiply by scale
		voxel_centroid.x = float(csv_line[0]) * scale
		voxel_centroid.y = float(csv_line[1]) * scale
		voxel_centroid.z = float(csv_line[2]) * scale
		for i in range(3, csv_line.size()):
			voxel.append(float(csv_line[i]))
```

2023-10-05 04:02 UTC, bquan0 commented
I tried adding the simplification, but ran into an `invalid index` error when loading the game. Must be an edge case when I get a csv line from the end of the file that doesn't have any voxel data (I think my generation python script must put a newline after all the voxel data lines). I fixed this by adding an if statement to check if the `csv_line` has 5 items.

2023-10-05 09:50 UTC, gonuke approved these changes
LGTM - Thanks @bquan0

2023-10-05 09:51 UTC, merged